# Generated by Django 5.1.6 on 2025-03-10 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='file',
        ),
        migrations.AddField(
            model_name='request',
            name='filename',
            field=models.CharField(default='unknown_file', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
